export const types = {
  // HOME
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',

  // ROOM
  SET_ROOM_ID: 'SET_ROOM_ID',
  SET_ROOM_STATE: 'SET_ROOM_STATE',
  SET_SPOTIFY_API: 'SET_SPOTIFY_API',
  SET_SPOTIFY_PLAYER: 'SET_SPOTIFY_PLAYER',
  SET_SPOTIFY_PLAYER_READY: 'SET_SPOTIFY_PLAYER_READY',
  SET_DEVICE_ID: 'SET_DEVICE_ID',
  EXIT_ROOM: 'EXIT_ROOM',


  // PLAYER
  PAUSE: 'PAUSE',
  PLAY: 'PLAY',
  CHANGE_TRACK: 'CHANGE_TRACK',
  DELETE_TRACK: 'DELETE_TRACK',
  ADD_TRACK: 'ADD_TRACK',
};
