const types = {
    // HOME
    LOGIN_LOADING: 'LOGIN_LOADING',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',

    // ROOM
    SET_ROOM_ID: 'SET_ROOM_ID',
    SET_ROOM_STATE: 'SET_ROOM_STATE',
    SET_SPOTIFY_API: 'SET_SPOTIFY_API',
    SET_SPOTIFY_PLAYER: 'SET_SPOTIFY_PLAYER',

    // PLAYER
    PAUSE: 'PAUSE',
    PLAY: 'PLAY',
    CHANGE_TRACK: 'CHANGE_TRACK',
    DELETE_TRACK: 'DELETE_TRACK',
    ADD_TRACK: 'ADD_TRACK',
}

export default types


